### ISSUE TITLE
Round down values generated from geocontext

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/geocontext#107]
# Problem

WMS getfeature info returns all the values stored for the raster layers. We need to round them to either 2 or 3 decimal places

# Solution

Round the numbers

**Comment by andretheronsa** [comment]
@NyakudyaA Is it safe to round down values for all any layer? Should it be only for WMS or any float value?

**Comment by NyakudyaA** [comment]
> @NyakudyaA Is it safe to round down values for all any layer? Should it be only for WMS or any float value?

It’s for all getfeatureinfo requests. So I think all float values
