### ISSUE TITLE
River name function should be handled the same as other registries

### ISSUE THREAD

**Issue by andretheronsa** [kartoza/geocontext#117]
Currently the river name api view is a function that calls its own database connection with a different pattern than context groups / collections.

Querying the Rivername should be handled the same as other data - possibly add a database query type

**Comment by NyakudyaA** [comment]
@andretheronsa I have added Postgres API to the postgis.kartoza.com so maybe you need to use this rather than connect to DB directly

**Comment by andretheronsa** [comment]
@NyakudyaA Thank you, that is great - I am working on Geocontext 2.0 now - since many things changed. I should have it ready by the end of this week and I will add this.

**Comment by NyakudyaA** [comment]
@Fanevanjanahary currently this function is using a PostgreSQL database function i.e https://github.com/kartoza/geocontext/issues/88 but this basically means the API is accessing the database directly and there is no way to get the following

 *collection
 *  group
 * service
 as the function is kind of standalone

I have additionally added a layer in geoserver which can be accessed from https://maps.kartoza.com/geoserver/kartoza/wms?service=WMS&version=1.1.0&request=GetMap&layers=kartoza:river_name&bbox=1831085.1652849577,-4139213.1300405697,3657706.640180942,-2526627.791405775&width=768&height=678&srs=EPSG:3857&format=application/openlayers

But we would need to pass a lat, long value when querying it using the GeoServer parametric views https://docs.geoserver.geo-solutions.it/edu/en/adding_data/add_sqllayers.html where you append the following `&viewparams=latitude:24;longitude:-27` to the wms request. 
You can decide how you want to implement it
