### ISSUE TITLE
Add offer tier model

### ISSUE THREAD

**Issue by fanevanjanahary** [kartoza/geocontext#172]
![Untitled Diagram drawio](https://user-images.githubusercontent.com/12623986/164637651-4e2dc7c3-1c40-49c0-8d1e-648182c42145.png)

**Comment by dimasciput** [comment]
@Fanevanjanahary why not put the description in the offer_tier table directly?

**Comment by fanevanjanahary** [comment]
Alright thank you @dimasciput
