### ISSUE TITLE
Populate json files with  missing temperature layers and boundary layers.

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/geocontext#33]
# Problem

it would be good to have:
- [x] Country
- [x] Province
- [x] District
- [x] Municipality
- [x] Parcel / Farm

All these layers are available from maps.kartoza.com and will be added to the json file.

Some other layers are missing for climate

The monthly mean temp and monthly mean stddev temp that are missing months

cc @timlinux

**Comment by gubuntu** [comment]
done
