### ISSUE TITLE
Update geocontext

### ISSUE THREAD

**Issue by dimasciput** [kartoza/geocontext#37]
- Update geocontext data
- Update context layers for healhtyriver and ledet

**Comment by gubuntu** [comment]
@NyakudyaA to liaise with @dimasciput about title format, nested admin hierarchy, numerical precision

**Comment by dimasciput** [comment]
@NyakudyaA the political boundary doesn't have any value 

```
 "context_group_values": [
    {
      "service_registry_values": [
        {
          "key": "sa_provinces", 
          "query_type": "WFS", 
          "description": null, 
          "value": null, 
          "name": "South Africa Provinces"
        }, 
        {}, 
        {}, 
        {}
      ], 
      "name": "Administrative Boundary", 
      "key": "political_boundary_group"
    }, 
```

**Comment by NyakudyaA** [comment]
@dimasciput which file are you looking at. Please take a look at https://github.com/kartoza/geocontext/blob/develop/django_project/base/management/commands/geocontext.json#L65

**Comment by dimasciput** [comment]
@NyakudyaA no this is data that I got from the political boundary layer. Check here : https://staging.limpopobims.kartoza.com/en/admin/bims/locationsite/1165/change/

**Comment by NyakudyaA** [comment]
@dimasciput I think I understand what is wrong. There is a Ledet collection which no longer exists so that's why it is returning empty values. I will add it and everything should be back to normal

**Comment by NyakudyaA** [comment]
@dimasciput if you make an API call to geocontext you are basically using a point to determine what values are there. How do we just make a general call to see which layers are available in a collection/group? I think the issue is that at some point you would not expect to get values at some of the layers if there is no layer at that point

**Comment by gubuntu** [comment]
geocontext should really just be a WPS (or we wrap it as a WPS) 

then it can respond to a GetCapabilities request

**Comment by NyakudyaA** [comment]
All the layers have been updated. All combinations are now valid and we have full complete months
