### ISSUE TITLE
We need a more beautiful landing page

### ISSUE THREAD

**Issue by timlinux** [kartoza/geocontext#43]
# Problem

We can do better than this right?

<img width="1666" alt="screenshot 2018-11-12 at 14 42 30" src="https://user-images.githubusercontent.com/178003/48348170-317d3f80-e689-11e8-9a6e-c84767e2e668.png">

# Proposed solution

- [x] Add some margins on the left and right of the page so it is not full width
- [x] Add some white space between the menu and content
- [x] Put a nice big icon in the jumbotron

![icon](https://user-images.githubusercontent.com/178003/48348579-748be280-e68a-11e8-96a7-012321588a5e.png)

- [x] Add some informative text as below:

GeoContext is a service that will fetch interesting data for a geographic position. It is an API that you can use to integrate this information into your own web site. The API returns JSON documents which enumerate any information found for the point you specify.

GeoContext can connect to various different types of services such as WMS and WFS to collate the point information. You can configure more services as needed and collate a number of services into a group. A number of groups can be combined into a collection.

Currently, the service is free to use, in the future we may charge a subscription to use it.

**Comment by timlinux** [comment]
Alternative version @Christiaanvdm 

![icon](https://user-images.githubusercontent.com/178003/48369490-62786700-e6bf-11e8-99d3-8534fd883afa.png)

**Comment by Christiaanvdm** [comment]
The landing page has been updated regarding layout. It will not work well on smaller devices due to how bootstrap's carousel works with text. Should work well responsively for medium and larger devices on landscape.

Will still incorporate the logo as the final component. A transition would likely round it off nicely.

<img width="1440" alt="screenshot 2018-11-13 at 10 41 19" src="https://user-images.githubusercontent.com/34506346/48401228-3c8baa80-e731-11e8-89c4-c5a914e2f2e9.png">

**Comment by dimasciput** [comment]
@Christiaanvdm can you share the screenshot for the smaller device ?

**Comment by Christiaanvdm** [comment]
@dimasciput 

<img width="664" alt="screenshot 2018-11-14 at 08 59 45" src="https://user-images.githubusercontent.com/34506346/48465523-b8e2c400-e7eb-11e8-88b0-9a2743b6dba9.png">

I don't think bootstrap renders the slide text for sm and possibly m devices. I think it would be best if for those sizes I just implement a more basic text output?
