### ISSUE TITLE
We need a favicon

### ISSUE THREAD

**Issue by timlinux** [kartoza/geocontext#45]
Please use the final icon from https://github.com/kartoza/geocontext/issues/43 to make a favicon for the site and make sure it is used everywhere.

**Comment by Christiaanvdm** [comment]
A favicon has been added to the Django site's static files called favicon.png - it is readily replaceable but appears as follows in Chrome (confirmed working in Safari and Firefox):

<img width="1439" alt="screenshot 2018-11-13 at 09 31 43" src="https://user-images.githubusercontent.com/34506346/48397621-00ebe300-e727-11e8-9ec9-55e46a2775a6.png">
