### ISSUE TITLE
SSL Support needed

### ISSUE THREAD

**Issue by timlinux** [kartoza/geocontext#46]
Please ask @dimasciput to show you how he sets up certbot and configure and deploy if for GeoContext.

**Comment by dimasciput** [comment]
@Christiaanvdm 
It's pretty easy with the rancher, please see this : 
https://www.digitalocean.com/community/tutorials/how-to-secure-your-rancher-web-app-with-let-s-encrypt-on-ubuntu-16-04

**Comment by Christiaanvdm** [comment]
Seems Dimas did all the work already :) I believe it is working correctly.

I added: 
```
frontend 80
acl lepath path_beg -i /.well-known/acme-challenge
redirect scheme https code 301 if  !lepath !{ ssl_fc }
```
to the `Custom haxproxy.cfg` and tested it using curl successfully as indicated by the digitalocean link above.
