### ISSUE TITLE
We need to support ESRI rest services

### ISSUE THREAD

**Issue by timlinux** [kartoza/geocontext#48]
There are many ESRI servers out there - we should support using them as a layer source too.

See e.g. https://portal.environment.gov.za/server/rest/services/Corp/ProtectedAreas/MapServer/ for an example server we could be using.

**Comment by Christiaanvdm** [comment]
Does this imply we want to be able to access the data via the service's ``f=lyr`` formatted output and adapting the ArcGIS output or rather pulling the data via another method (eg. ``f=jsapi``) and extracting the layer data that way?
@timlinux

**Comment by timlinux** [comment]
Logging request proxy: https://gis.stackexchange.com/questions/282662/is-there-any-easy-way-to-see-the-requests-qgis-makes-to-a-remote-server?rq=1

**Comment by timlinux** [comment]
Alternative approach for logging requests:

https://lists.osgeo.org/pipermail/qgis-developer/2018-October/054921.html

**Comment by Christiaanvdm** [comment]
Request eg 1:
```
https://portal.environment.gov.za/server/rest/services/Corp/ProtectedAreas/MapServer//identify?f=json&geometryType=esriGeometryPoint&geometry=%7Bx: 21.982197, y: -33.381190%7D&layers=all:10&imageDisplay=581,461,96&mapExtent=16.276867,-35.104675,33.541434,-21.405940&tolerance=10
```

Request eg 2:
```
https://portal.environment.gov.za/server/rest/services/Corp/ProtectedAreas/MapServer//identify?f=json&geometryType=esriGeometryPoint&geometry=%7Bx: 19.307824, y: -32.638309%7D&layers=all:7&imageDisplay=581,461,96&mapExtent=16.276867,-35.104675,33.541434,-21.405940&tolerance=10
```
