### ISSUE TITLE
Support for climate data

### ISSUE THREAD

**Issue by timlinux** [kartoza/geocontext#5]
We have another use case where we will receive numerical data back e.g. temperature, rainfall etc. And another source type that we should support so that we can fetch data from ArcGIS Rest services. I would like @NyakudyaA to register these layers as. 'Climate' context group.

Elsenburg publishes all the climate layers as ArcGIS Rest services here:

https://gis.elsenburg.com/arcgis/rest/services/Climate/MapServer

You can easily add them to QGIS like this:

![screen shot 2018-06-21 at 13 32 58](https://user-images.githubusercontent.com/178003/41717920-9ed21118-755b-11e8-8143-6287e1c3eb15.png)

Or to OpenLayers like this:

https://openlayers.org/en/latest/examples/vector-esri.html

And we can do point queries from python like this

https://github.com/Schwanksta/python-arcgis-rest-query

**Comment by timlinux** [comment]
@ismailsunni can you work to add support for ArcGIS Rest Services if it is not a huge job.

Admire can you add those layers to your spreadsheet?

**Comment by ismailsunni** [comment]
@timlinux can you give more specific request that you want to do? It seems your ArcGIS Rest services support WMS. Should we just go with adding WMS support?

**Comment by timlinux** [comment]
So I got some feedback from the org hosting those data:

> Although the Elsenburg  map services are publically visible, we are not promoting or allowing direct public usage.  All users must please refrain from doing so.  The data from the SA Atlas of Climatology and Agrohydrology is available for download from the SA Risk & Vulnerability Atlas:  http://sarva2.dirisa.org/

So the task is:

- [ ] @NyakudyaA to pull down those datasets and publish them on maps.kartoza.com in our geoserver
- [ ] @ismailsunni to register those WMS sources in our geocontext in a new 'Bioclimatic' group

@ismailsunni I don't know if we have already the provenance as a field, but we need to make sure we have stored the origin of each datasets and any licensing and notes info.

**Comment by ismailsunni** [comment]
@NyakudyaA I think we can close this after your update on the geocontext.json, right?

**Comment by NyakudyaA** [comment]
@ismailsunni I will close this sometime later today. Need to add more to the json

**Comment by NyakudyaA** [comment]
@ismailsunni I have published all the climate layers so I will close this issue
