### ISSUE TITLE
GeoContext API should return GeoJSON

### ISSUE THREAD

**Issue by timlinux** [kartoza/geocontext#53]
I just realised that the document we get back is not a geojson document.

It would be interesting to see if we can also / instead deliver it as a GeoJSON document so that it can be used easily in web mapping clients. I don't know if it would work well given the nested structure of the geocontext document though.

**Comment by gubuntu** [comment]
won't geometry make it too heavy and also start treading on OWS - we don't want to reinvent WFS / WPS here 

could we consider wrapping this as a a WPS?

**Comment by timlinux** [comment]
Adding the point coordinates isn't going to make much difference in the payload size.....and will allow users to map the returned data.

I don;t think there is any overlap with WPS/WFS in what we are doing.

Implementing as WPS: I dont think I want to do that - the code is very lightweight right now and I would like to keep it like that.
