### ISSUE TITLE
Extent models to include graphable column

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/geocontext#65]
# Problem
I am trying to import data into the geocontext service and I get the following error.

```

   Number of Context Group 17
   Number of Context Collection 5
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
psycopg2.ProgrammingError: column geocontext_contextgroup.graphable does not exist
LINE 1: ...ription", "geocontext_contextgroup"."group_type", "geocontex...

```

# Solution
Make happy
                                                             ^

**Comment by Christiaanvdm** [comment]
@NyakudyaA Have you pulled the latest repo and migrated? 
- Sorry some of my migrations weren't added. I have addressed this.

**Comment by NyakudyaA** [comment]
LGTM. I can deploy the site properly
