### ISSUE TITLE
How to test arc rest services

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/geocontext#67]
# Problem
 When importing data into the service the following message
```
Load Context Groups....
   Context Group A test of the placename type is loaded
No CSR registered for arc_rest_test_is
No CSR registered for arc_rest_test_the
No CSR registered for arc_rest_test_best
```
Usually indicates that the service was not successfully imported.

an example in the app

![not-working](https://user-images.githubusercontent.com/2510900/49586994-67050800-f96b-11e8-8eaa-7d19cfd5b372.png)

Working in the app
![working](https://user-images.githubusercontent.com/2510900/49587012-71270680-f96b-11e8-927d-6d0e85d08710.png)

**Comment by Christiaanvdm** [comment]
Sorry, I forgot to remove the group as well (whilst I was busy replacing my test data with something better suited for an end user example) after removing the two ARC Service Context Registiries. I will rectify this today.
